### ISSUE TITLE
urllib.error.HTTPError

### ISSUE THREAD

**Issue by NeKroFR** [NeKroFR/PhoneAnalyzer#1]
# Too Many Requests
```
Traceback (most recent call last):
  File "PhoneAnalyzer.py", line 75, in <module>
    analyse(number)
  File "PhoneAnalyzer.py", line 61, in analyse
    for result in request:
  File "/home/nk0/.local/lib/python3.8/site-packages/googlesearch/__init__.py", line 305, in search
    html = get_page(url, user_agent, verify_ssl)
  File "/home/nk0/.local/lib/python3.8/site-packages/googlesearch/__init__.py", line 174, in get_page
    response = urlopen(request)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests
```

**Comment by NeKroFR** [comment]
should be good now, I added a delay beetween the requests

**Comment by NeKroFR** [comment]
still don't work for phone numbers with a lot of results online

**Comment by NeKroFR** [comment]
should be patched even tho you might get the error again if you use the script multiple times on a short period of time.
